// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "BangBangShooter.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

BangBangShooter::BangBangShooter(double speed): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
	mspeed = speed;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void BangBangShooter::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void BangBangShooter::Execute() {
	if (mspeed > RobotMap::shootershooterMotor1->GetEncVel() || mspeed > RobotMap::shootershooterMotor2->GetEncVel())
	{
		RobotMap::shootershooterMotor1->Set(1.0);
		RobotMap::shootershooterMotor2->Set(1.0);
	}
	else
	{
		RobotMap::shootershooterMotor1->Set(0.0);
		RobotMap::shootershooterMotor2->Set(0.0);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool BangBangShooter::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void BangBangShooter::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void BangBangShooter::Interrupted() {

}
