// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "IntakeVariableLift.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeVariableLift::IntakeVariableLift(double lift_voltage): Command() {
    m_lift_voltage = lift_voltage;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void IntakeVariableLift::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void IntakeVariableLift::Execute() {
    //TODO implement lift control
    //RobotMap::intake_lift_motrs
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeVariableLift::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void IntakeVariableLift::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeVariableLift::Interrupted() {

}
