// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShooterVariableControl.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterVariableControl::ShooterVariableControl(double shooter_voltage, double roller_voltage): Command() {
    m_shooter_voltage = shooter_voltage;
    m_roller_voltage = roller_voltage;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterVariableControl::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ShooterVariableControl::Execute() {
    RobotMap::shooterRollerMotor->Set(m_roller_voltage);

    RobotMap::shooterMotor1->Set(m_shooter_voltage);
    RobotMap::shooterMotor2->Set(m_shooter_voltage);
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterVariableControl::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ShooterVariableControl::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterVariableControl::Interrupted() {

}
