#ifndef SpeedShooterControl_H
#define SpeedShooterControl_H

#include "Commands/Subsystem.h"
#include "../Robot.h"

class SpeedShooterControl: public Command
{
public:
	SpeedShooterControl(double speed_);
	void Initialize();
	void Execute();
	bool IsFinished();
	void End();
	void Interrupted();
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    double speed;
    int count;
};

#endif
