// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "TankDrive.h"
#include ".../Subsystems/Chassis.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TankDrive::TankDrive(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void TankDrive::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void TankDrive::Execute() {
	//Left Side
	RobotMap::chassisleftMotor1->Set(Robot::oi->getdriver()->GetRawAxis(1));
	RobotMap::chassisleftMotor2->Set(Robot::oi->getdriver()->GetRawAxis(1));
	RobotMap::chassisleftMotor3->Set(Robot::oi->getdriver()->GetRawAxis(1));

	//Right Side
	RobotMap::chassisrightMotor1->Set(Robot::oi->getdriver()->GetRawAxis(5) * 1);
	RobotMap::chassisrightMotor2->Set(Robot::oi->getdriver()->GetRawAxis(5) * 1);
	RobotMap::chassisrightMotor3->Set(Robot::oi->getdriver()->GetRawAxis(5) * 1);


}

// Make this return true when this Command no longer needs to run execute()
bool TankDrive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void TankDrive::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TankDrive::Interrupted() {

}
