// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ToggleShooter.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ToggleShooter::ToggleShooter(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ToggleShooter::Initialize() {


}

// Called repeatedly when this Command is scheduled to run
void ToggleShooter::Execute() {
	if (RobotMap::shooterliftShooter->Get() == DoubleSolenoid::kForward)
		RobotMap::shooterliftShooter->Set(DoubleSolenoid::kReverse);

	else if (RobotMap::shooterliftShooter->Get() == DoubleSolenoid::kReverse)
		RobotMap::shooterliftShooter->Set(DoubleSolenoid::kForward);
}

// Make this return true when this Command no longer needs to run execute()
bool ToggleShooter::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ToggleShooter::End() {

}

void ToggleShooter::Interrupted(){

}

