// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DefaultChassis.h"
#include "Commands/DefaultIntake.h"
#include "Commands/DefaultShooter.h"
#include "Commands/IntakeVariableLift.h"
#include "Commands/IntakeVariablePull.h"
#include "Commands/ShooterVariableControl.h"
#include "Commands/TestChassis.h"
#include "Commands/TestIntake.h"
#include "Commands/TestShoot.h"
#include "Commands/ToggleDriveShifter.h"
#include "Commands/ToggleShooterLifter.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    coDriver.reset(new Joystick(1));
    
    coButtonR3.reset(new JoystickButton(coDriver.get(), 10));
    coButtonR3->WhileHeld(new AutonomousCommand());
    coButtonL3.reset(new JoystickButton(coDriver.get(), 9));
    coButtonL3->WhileHeld(new AutonomousCommand());
    coButtonStart.reset(new JoystickButton(coDriver.get(), 8));
    coButtonStart->WhileHeld(new AutonomousCommand());
    coButtonBack.reset(new JoystickButton(coDriver.get(), 7));
    coButtonBack->WhileHeld(new AutonomousCommand());
    coButtonRB.reset(new JoystickButton(coDriver.get(), 6));
    coButtonRB->WhileHeld(new AutonomousCommand());
    coButtonLB.reset(new JoystickButton(coDriver.get(), 5));
    coButtonLB->WhileHeld(new AutonomousCommand());
    coButtonY.reset(new JoystickButton(coDriver.get(), 4));
    coButtonY->WhileHeld(new AutonomousCommand());
    coButtonX.reset(new JoystickButton(coDriver.get(), 3));
    coButtonX->WhileHeld(new AutonomousCommand());
    coButtonB.reset(new JoystickButton(coDriver.get(), 2));
    coButtonB->WhileHeld(new AutonomousCommand());
    coButtonA.reset(new JoystickButton(coDriver.get(), 1));
    coButtonA->WhileHeld(new AutonomousCommand());
    driver.reset(new Joystick(0));
    
    dButtonR3.reset(new JoystickButton(driver.get(), 10));
    dButtonR3->WhileHeld(new AutonomousCommand());
    dButtonL3.reset(new JoystickButton(driver.get(), 9));
    dButtonL3->WhileHeld(new AutonomousCommand());
    dButtonStart.reset(new JoystickButton(driver.get(), 8));
    dButtonStart->WhileHeld(new AutonomousCommand());
    dButtonBack.reset(new JoystickButton(driver.get(), 7));
    dButtonBack->WhileHeld(new AutonomousCommand());
    dButtonRB.reset(new JoystickButton(driver.get(), 6));
    dButtonRB->WhileHeld(new AutonomousCommand());
    dButtonLB.reset(new JoystickButton(driver.get(), 5));
    dButtonLB->WhileHeld(new AutonomousCommand());
    dButtonY.reset(new JoystickButton(driver.get(), 4));
    dButtonY->WhileHeld(new AutonomousCommand());
    dButtonX.reset(new JoystickButton(driver.get(), 3));
    dButtonX->WhileHeld(new AutonomousCommand());
    dButtonB.reset(new JoystickButton(driver.get(), 2));
    dButtonB->WhileHeld(new AutonomousCommand());
    dButtonA.reset(new JoystickButton(driver.get(), 1));
    dButtonA->WhileHeld(new AutonomousCommand());

    // SmartDashboard Buttons
    SmartDashboard::PutData("TestIntake", new TestIntake());
    SmartDashboard::PutData("TestChassis", new TestChassis());
    SmartDashboard::PutData("TestShoot", new TestShoot());
    SmartDashboard::PutData("ToggleShooterLifter", new ToggleShooterLifter());
    SmartDashboard::PutData("ToggleDriveShifter", new ToggleDriveShifter());
    SmartDashboard::PutData("IntakeVariablePull: off", new IntakeVariablePull(0));
    SmartDashboard::PutData("IntakeVariableLift: off", new IntakeVariableLift(0));
    SmartDashboard::PutData("ShooterVariableControl: shooterOff", new ShooterVariableControl(0.0, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter50P", new ShooterVariableControl(0.5, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter55P", new ShooterVariableControl(0.55, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter60P", new ShooterVariableControl(0.6, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter65P", new ShooterVariableControl(0.65, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter70P", new ShooterVariableControl(0.7, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter75P", new ShooterVariableControl(0.75, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter80P", new ShooterVariableControl(0.8, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter85P", new ShooterVariableControl(0.85, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter90P", new ShooterVariableControl(0.9, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter95P", new ShooterVariableControl(0.95, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooter100P", new ShooterVariableControl(1.0, 0));
    SmartDashboard::PutData("ShooterVariableControl: shooterReverse25_25P", new ShooterVariableControl(-0.25, -0.25));
    SmartDashboard::PutData("ShooterVariableControl: shooterReverse25_50p", new ShooterVariableControl(-0.25, -0.5));
    SmartDashboard::PutData("ShooterVariableControl: shooterReverse50_50P", new ShooterVariableControl(-0.5, -0.5));
    SmartDashboard::PutData("DefaultChassis", new DefaultChassis());
    SmartDashboard::PutData("DefaultShooter", new DefaultShooter());
    SmartDashboard::PutData("DefaultIntake", new DefaultIntake());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getdriver() {
   return driver;
}

std::shared_ptr<Joystick> OI::getcoDriver() {
   return coDriver;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
