// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::chassisleftMotor1;
std::shared_ptr<CANTalon> RobotMap::chassisleftMotor2;
std::shared_ptr<CANTalon> RobotMap::chassisleftMotor3;
std::shared_ptr<CANTalon> RobotMap::chassisrightMotor1;
std::shared_ptr<CANTalon> RobotMap::chassisrightMotor2;
std::shared_ptr<CANTalon> RobotMap::chassisrightMotor3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    chassisleftMotor1.reset(new CANTalon(1));
    lw->AddActuator("Chassis", "leftMotor1", chassisleftMotor1);
    
    chassisleftMotor2.reset(new CANTalon(2));
    lw->AddActuator("Chassis", "leftMotor2", chassisleftMotor2);
    
    chassisleftMotor3.reset(new CANTalon(3));
    lw->AddActuator("Chassis", "leftMotor3", chassisleftMotor3);
    
    chassisrightMotor1.reset(new CANTalon(4));
    lw->AddActuator("Chassis", "rightMotor1", chassisrightMotor1);
    
    chassisrightMotor2.reset(new CANTalon(5));
    lw->AddActuator("Chassis", "rightMotor2", chassisrightMotor2);
    
    chassisrightMotor3.reset(new CANTalon(6));
    lw->AddActuator("Chassis", "rightMotor3", chassisrightMotor3);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
